# This is a basic workflow that is manually triggered
name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Run Klaatu on Firefox Release'
        default: 'control'
        required: true
        type: string
env:
  MOZ_HEADLESS: 1
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Chocolatey
      shell: pwsh
      run: Set-ExecutionPolicy Bypass -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    - name: Install Dependencies
      shell: pwsh
      run: choco install jdk8 selenium-gecko-driver selenium 
    - name: Install Firefox Release
      shell: pwsh
      run: choco install firefox
    - name: Setup tests
      shell: bash
      run: ./setup_script.sh
    - run: tox -e bdd-tests -- --experiment-branch ${{ inputs.name }} --experiment-json tests/fixtures/test_experiment.json -k navigate_to_the_supplied_url
